name: Actualizar README con contribuciones

on:
  schedule:
    - cron: '0 0 * * *' # Ejecuta una vez al día
  workflow_dispatch: # Permite ejecución manual

jobs:
  actualizar-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Obtener repositorio
        uses: actions/checkout@v2

      - name: Configurar Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'  # Cambia a Node.js 18

      - name: Obtener últimas contribuciones
        run: |
          # Usar import dinámico para el módulo ECMAScript
          node << 'EOF'
          (async () => {
            const { Octokit } = await import('@octokit/core');
            const fs = require('fs');

            const usuario = 'srnovus';
            const repositorio = 'fedired';
            const octokit = new Octokit();

            async function obtenerContribuciones() {
                const respuesta = await octokit.request('GET /repos/{owner}/{repo}/commits', {
                    owner: 'fedired-dev',
                    repo: repositorio,
                    per_page: 5
                });

                const contribuciones = respuesta.data.map(commit => {
                    return `- [${commit.commit.message}](${commit.html_url}) (${commit.commit.author.date.split('T')[0]})`;
                }).join('\n');

                return contribuciones;
            }

            async function actualizarReadme() {
                const contribuciones = await obtenerContribuciones();
                const rutaReadme = './README.md';
                const contenidoReadme = fs.readFileSync(rutaReadme, 'utf8');

                const nuevoContenido = contenidoReadme.replace(
                    /<!--INICIO_SECCION:contribuciones-->[\s\S]*<!--FIN_SECCION:contribuciones-->/,
                    `<!--INICIO_SECCION:contribuciones-->\n${contribuciones}\n<!--FIN_SECCION:contribuciones-->`
                );

                fs.writeFileSync(rutaReadme, nuevoContenido);
            }

            await actualizarReadme();
          })();
          EOF

      - name: Hacer commit y push de los cambios
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add README.md
          git commit -m "Actualizar contribuciones recientes"
          git push
