name: Actualizar README con contribuciones

on:
  schedule:
    - cron: '0 0 * * *' # Ejecuta una vez al día a la medianoche
  workflow_dispatch: # Permite ejecución manual desde Actions

jobs:
  actualizar-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Obtener repositorio
        uses: actions/checkout@v2

      - name: Configurar Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Obtener últimas contribuciones
        run: |
          # Instalar octokit para interactuar con la API de GitHub
          npm install @octokit/core
          
          # Crear script para obtener las contribuciones recientes
          node << 'EOF'
          const { Octokit } = require("@octokit/core");
          const fs = require('fs');

          const usuario = 'srnovus';
          const repositorio = 'fedired';
          const octokit = new Octokit();

          async function obtenerContribuciones() {
              const respuesta = await octokit.request('GET /repos/{owner}/{repo}/commits', {
                  owner: 'fedired-dev',
                  repo: repositorio,
                  per_page: 5
              });

              const contribuciones = respuesta.data.map(commit => {
                  return `- [${commit.commit.message}](${commit.html_url}) (${commit.commit.author.date.split('T')[0]})`;
              }).join('\n');

              return contribuciones;
          }

          async function actualizarReadme() {
              const contribuciones = await obtenerContribuciones();
              const rutaReadme = './README.md';
              const contenidoReadme = fs.readFileSync(rutaReadme, 'utf8');

              const nuevoContenido = contenidoReadme.replace(
                  /<!--INICIO_SECCION:contribuciones-->[\s\S]*<!--FIN_SECCION:contribuciones-->/,
                  `<!--INICIO_SECCION:contribuciones-->\n${contribuciones}\n<!--FIN_SECCION:contribuciones-->`
              );

              fs.writeFileSync(rutaReadme, nuevoContenido);
          }

          actualizarReadme();
          EOF

      - name: Hacer commit y push de los cambios
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add README.md
          git commit -m "Actualizar contribuciones recientes"
          git push
